coventGarden/coventGarden/urls.py
from django.contrib import admin

from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("studios.urls")),

]

coventGarden/studios/urls.py
from django.urls import path
from django.conf.urls.static import static
from coventGarden import settings
from studios import views

urlpatterns = [
    path('', views.placeholder, name='placeholder'),

    # Navigation
    path('', views.HomeView.as_view(), name='home'),
    path('actualites/', views.NewsView.as_view(), name='news'),
    path('studios/', views.StudiosView.as_view(), name='studios'),
    path('concert/', views.ConcertView.as_view(), name='concert'),
    path('bar/', views.BarView.as_view(), name='bar'),
    path('reservation/', views.BookingView.as_view(), name='booking'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cgu/', views.EulaView.as_view(), name='eula'),

    # Account: Login / Logout
    path('compte/connexion/', views.AccountSignInFormView.as_view(),
         name='account_sign_in_form'),
    path('compte/deconnexion/', views.account_log_out,
         name='account_log_out'),

    # Account: Sign Up
    path('compte/inscription/', views.AccountSignUpFormView.as_view(),
         name='account_sign_up_form'),
    path('compte/inscription/envoi/', views.AccountSignUpDoneView.as_view(),
         name="account_sign_up_done"),
    path('compte/inscription/confirmation/<uidb64>/<token>/', views.AccountSignUpConfirmView.as_view(),
         name='account_sign_up_confirm'),
    path('compte/inscription/echec/', views.AccountSignUpFailedView.as_view(),
         name='account_sign_up_failed'),
    path('compte/inscription/verification/', views.AccountSignUpAgainView.as_view(),
         name='account_sign_up_again'),

    # Account: Password Forgot
    path('compte/mot-de-passe-oublie/', views.AccountPasswordForgotForm.as_view(),
         name='account_password_forgot_form'),
    path('compte/mot-de-passe-oublie/envoi/', views.AccountPasswordForgotDone.as_view(),
         name='account_password_forgot_done'),
    path('compte/mot-de-passe-oublie/modification/<uidb64>/<token>/', views.AccountPasswordForgotConfirm.as_view(),
         name='account_password_forgot_confirm'),
    path('compte/mot-de-passe-oublie/confirmation/', views.AccountPasswordForgotComplete.as_view(),
         name='account_password_forgot_complete'),

    # Profile
    path('compte/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('compte/modifier/', views.ProfileUpdateView.as_view(), name='profile_update'),

    # Groups
    path('compte/mes_groupes/', views.GroupDetailView.as_view(), name='groups_detail'),
    path('compte/mes_groupes/ajouter/', views.GroupCreateView.as_view(), name='groups_create'),
    path('compte/mes_groupes/modifier/<int:group_id>/', views.GroupUpdateView.as_view(), name='groups_update'),
    path('compte/mes_groupes/supprimer/<int:group_id>/', views.GroupDeleteView.as_view(), name='groups_delete'),

    # Bookings
    path('compte/mes_reservations/', views.BookingsDetailView.as_view(), name='bookings_detail'),
    path('compte/mes_reservations/ajouter/', views.BookingsCreateView.as_view(), name='bookings_create'),

    # Pro Area
    path('compte/espace_pro/', views.ProAreaView.as_view(), name='pro_area'),

    # Planning
    path('all_events/', views.all_events, name='all_events'),
    path('add_event/', views.add_event, name='add_event'),
    path('update/', views.update, name='update'),
    path('remove/', views.remove, name='remove'),
    path('calendar/', views.calendar_view, name='calendar'),

    # Booking
    path('api/all_booking/', views.all_booking, name='all_booking'),
    path('api/all_booking_event/', views.all_booking_event, name='all_booking_event'),
    path('set-reservation/<int:id_reservation>/', views.set_reservation, name='set_reservation'),
    path('users/', views.list_users, name='list_users'),
    path('salles/', views.list_salles, name='list_salles'),
    path('paiement-accompte/', views.accompte, name='accompte'),
    # path('payment_successful', views.payment_successful, name='payment_successful'),
    # path('payment_cancelled', views.payment_cancelled, name='payment_cancelled'),
    path('stripe_webhook', views.stripe_webhook, name='stripe_web'),

    # WIP
    path('create-checkout-session/', views.payment, name='payment'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coventGarden/studios/models.py
from datetime import timedelta
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save

from .fields import *

# Create your models here.
"""
Account
    - CustomUser
    - CustomGroup
"""
class CustomUser(AbstractUser):
    username = MODEL_USERNAME
    email = MODEL_EMAIL
    last_name = MODEL_LAST_NAME
    first_name = MODEL_FIRST_NAME
    phone = MODEL_PHONE
    password = MODEL_PASSWORD
    password_confirm = MODEL_PASSWORD_CONFIRM
    # is_active = False by default when creating an account using the UserSignUpForm
    # my_groups (See CustomGroup)

    def __str__(self):
        return self.username

class CustomGroup(models.Model):
    user = models.ForeignKey(
        to=CustomUser,
        on_delete=models.CASCADE,
        related_name='my_groups'
    )
    name = MODEL_GROUP_NAME
    email = MODEL_GROUP_EMAIL
    phone = MODEL_GROUP_PHONE
    members = MODEL_MEMBERS
    genre = MODEL_GENRE
    facebook = MODEL_FACEBOOK
    instagram = MODEL_INSTAGRAM
    biography = MODEL_BIOGRAPHY
    technical_sheet = MODEL_TECHNICAL_SHEET
    logo = MODEL_LOGO
    validated = MODEL_VALIDATED

    def __str__(self):
        return f"{self.name}"





"""
Booking
    - Event
    - Salle
    - Reservation
"""
class Event(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200, default='Untitled Event')
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    recurrence = models.CharField(max_length=200, blank=True)
    date = models.DateField(default=timezone.now)

class Salle(models.Model):
    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)

    def __str__(self):
        return f'{self.name}'

class Reservation(models.Model):
    class Status(models.TextChoices):
        RESERVED = 'Reserver'
        INPROGRESS = 'En cours'

    # title = models.fields.CharField(default='Item', max_length=100)
    description = models.fields.CharField(max_length=1000)
    duration = models.fields.IntegerField(validators=[MinValueValidator(0)])
    date_start = models.DateTimeField(null=False)
    date_end = models.DateTimeField(null=False)
    price = models.fields.IntegerField(validators=[MinValueValidator(1)])
    status = models.fields.CharField(choices=Status.choices, max_length=20)
    salle = models.ForeignKey(Salle, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    is_active = models.BooleanField(default=True)





"""
Pro Area
    - Concert
"""
class Concert(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    groupe1 = models.ForeignKey(CustomGroup, on_delete=models.CASCADE, related_name='concerts_groupe1', null=True)
    groupe2 = models.ForeignKey(CustomGroup, on_delete=models.CASCADE, related_name='concerts_groupe2', null=True)
    groupe3 = models.ForeignKey(CustomGroup, on_delete=models.CASCADE, related_name='concerts_groupe3', null=True)
    date = models.DateField()
    validated = models.BooleanField(default=False)
    planning = models.OneToOneField(Event, on_delete=models.SET_NULL, blank=True, null=True)





"""
Payment
"""
class UserPayment(models.Model):
    app_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    payment_bool = models.BooleanField(default=False)
    stripe_checkout_id = models.CharField(max_length=500)


@receiver(post_save, sender=CustomUser)
def create_user_payment(sender, instance, created, **kwargs):
    if created:
        UserPayment.objects.create(app_user=instance)


#création freefriday

@receiver(post_save, sender=Concert)
def create_event(sender, instance, created, **kwargs):
    if instance.validated:
        description = f"FreeFriday en présence du groupe {instance.groupe1}, du groupe {instance.groupe2} et du groupe {instance.groupe3}"
        date = instance.date  # Supposons que `date` est la date du concert

        Event.objects.update_or_create(
             user=instance.user,
            title='FreeFriday',
            defaults={
                    'date': date,
                    'start_time': date + timedelta(hours=20, minutes=30),
                    'end_time': date + timedelta(hours=23, minutes=30),
                    'description': description
    }
)
        

coventGarden/studios/templates/studios/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.core.mail import send_mail

def home(request):
    return render(request, 'studios/home.html')

def news(request):
    return render(request, 'studios/news.html')

def studios(request):
    return render(request, 'studios/studios.html')

def bar(request):
    return render(request, 'studios/bar.html')

def pro_area(request):
    return render(request, 'studios/pro_area.html')

def contact(request):
    return render(request, 'studios/contact.html')

def booking(request):
    return render(request, 'studios/booking.html')

def account(request):
    return render(request, 'studios/account.html')

def sign_in(request):
    return render(request, 'studios/signin.html')

def sign_up(request):
    return render(request, 'studios/base/signup.html')

coventGarden/studios/templates/bar.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Page header -->
{% block page_header %}

<header class="page-header">
	<h1 class="page-title">{{title}}</h1>
</header>

{% endblock %}



<!-- Main content -->
{% block content %}

<!-- Content 1: Images -->
<div class="row">
	<!-- Left -->
	<div class="col-sm-5">
		<img class="navbar-brand" src="{% static 'studios/images/De_Sutter.png' %}">
	</div>

	<!-- Right -->
	<div class="col-sm-7">
		<img class="navbar-brand" src="{% static 'studios/images/photos-bar.jpg' %}">
	</div>
</div>

<!-- Content 2: Text -->
<h4 style="text-align:justify">Depuis de nombres années, le Covent Garden Studios fait confiance à la <a href="http://www.brasseriedesutter.com/" target="_blank">Brasserie De Sutter</a> pour leur fournir une bière artisanale de qualité.</h4>
<h4 style="text-align:justify">La Brasserie De Sutter est fondée par deux frères, Antoine et Frédéric, passionnés par la bière et par sa fabrication. En 2008, ils se lancent dans des tests de création de recettes et suite à l’obtention de leurs diplômes en agronomie ainsi qu’en brasserie, les premières bières voient le jour. Rapidement confortés par la qualité de leurs produits, les brasseurs installent une unité de production artisanale de 800 litres.</h4>  
<h4 style="text-align:justify">En janvier 2012, c’est le grand saut vers une fabrication maîtrisée et de plus grosse capacité grâce au déménagement de la Brasserie De Sutter à Gisors dans des locaux plus grands avec du matériel de brassage neuf et performant.</h4>

<!-- Content 3: Swiper -->
<div class="swiper mySwiper">
	<div class="swiper-wrapper">
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-ambree-rousse-dement-bree.png' %}" alt="Dément'brée"></div>
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-blanche-givree_1.png' %}" alt="Givrée"></div>
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-blonde-brin-de-folie.png' %}" alt="Brin de Folie"></div>
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-sombre-folle-brune.png' %}" alt="Folle Furieuse"></div>
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-fruits-rouges-folle-des-bo.png' %}" alt="Folle des bois"></div>
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-ipa-crazy-indian-pale-ale.png' %}" alt="Crazy - IPA"></div>
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-zinzin-quadruple-fermentat.png' %}" alt="Zin Zin"></div>
		<div class="swiper-slide"><img src="{% static 'studios/images/biere-artisanale-folies-de-sutter-ictis.jpg' %}" alt="Ictis - Bio"></div>
	</div>
</div>

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

	<!-- Slider CSS -->
	<link rel="stylesheet" href="{% static 'studios/css/slider.css' %}"/>

	<!-- Link Swiper's CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />

	<!-- Demo styles -->
	<style>
		.swiper {
		width: 100%;
		padding-top: 50px;
		padding-bottom: 50px;
		}

		.swiper-slide {
		background-position: center;
		background-size: cover;
		width: 240px;
		height: 240px;
		}

		.swiper-slide img {
		display: block;
		width: 100%;
		}
	</style>

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

	<!-- Swiper JS -->
	<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>

	<!-- Initialize Swiper -->
	<script>
		var swiper = new Swiper(".mySwiper", {
		  effect: "coverflow",
		  grabCursor: true,
		  centeredSlides: true,
		  slidesPerView: "auto",
		  coverflowEffect: {
			rotate: 35,
			stretch: 0,
			depth: 40,
			modifier: 1,
			slideShadows: false,
		  },
		  pagination: {
			el: ".swiper-pagination",
		  },
		  initialSlide: 2, // Affiche la 3e image (index 2) par défaut
		});
	</script>

{% endblock %}

coventGarden/studios/templates/booking.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Page header -->
{% block page_header %}

<header class="page-header">
	<h1 class="page-title">{{title}}</h1>
</header>

{% endblock %}



<!-- Main content -->
{% block content %}

<!-- Content 1 -->
<div class="stud">
	<div class="row">
		<!-- Left -->
		<div class="col-sm-6">
			<h2>Horaires :</h2><br>
			<table class="table-center">
				<tbody>
					<tr><td>Lundi - Vendredi</td><td>16h00 -  </td><td>00h00</td></tr>
					<tr><td>Samedi *</td><td>10h00 - </td><td>18h00</td></tr>
					<tr><td>Dimanche</td><td>13h00 - </td><td>21h00</td></tr>
				</tbody>
			</table>
			
			<!-- Add link concert-->
			<br>*Ouverture jusqu'à minuit les soirs de <a href="{% url 'concert' %}">concerts</a>.</p>
		</div>

		<!-- Right -->
		<div class="col-sm-6">
			<h2>Tarifs :</h2><br>
			<table class="table-center">
				<tbody>
					<tr><td>1 heure</td><td>20€</td></tr>
					<tr><td>2 heures</td><td>38€</td></tr>
					<tr><td>3 heures</td><td>54€</td></tr>
					<tr><td>4 heures</td><td>68€</td></tr>
					<tr><td>Heure supplémentaire</td><td>17€</td></tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<!-- Content 1 -->
{% for salle in salles %}
<div class="col-xs-12">
    <h3 class="text-center mt-4">{{ salle.name }}</h3>
    <br>
    <div id='calendar{{ salle.id }}'></div>
</div>
{% endfor %}


<div class="modal" id="confirmation-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Information de la réservation</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form id="confirm-form" action="{% url 'accompte' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="salle">Studios choisi :</label>
                        <input id="salleName" name="salleName" class="form-control" readonly required>
                    </div>
                    <div class="form-group">
                        <label for="start_date">Date et heure de début :</label>
                        <input type="datetime" name="date_start" id="startDate" readonly class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Date et heure de fin :</label>
                        <input type="datetime" name="date_end" id="endDate" class="form-control" readonly required>
                    </div>
                   
                    <input type="hidden" name="salle_id" id="idSalle">
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Confirmer</button>
                    <button type="button" id="cancel-btn" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

<link rel="stylesheet" href="{% static 'studios/css/booking.css' %}">

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

<!--script src='https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@6.1.8/index.global.min.js'></script-->
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>
<script src="{% static 'studios/js/booking.js' %}"></script>

{% endblock %}

coventGarden/studios/templates/concert.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Page header -->
{% block page_header %}

<header class="page-header">
	<h1 class="page-title">{{title}}</h1>
</header>

{% endblock %}



<!-- Main content -->
{% block content %}

<!-- Content 1 -->
<div class="row">
	<div class="col-sm-12"
		<div id="calendar"></div>
	</div>
</div>

<div class="row justify-content-center align-items-center text-center" style="margin-top: 20px;">
	<a class="btn btn-action btn-lg" href="{% url 'pro_area' %}" role="button">Demande de programmation</a>
</div>


{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

<link rel="stylesheet" href="{% static 'studios/css/concert.css' %}"/>

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

<script src="{% static 'studios/js/concert.js' %}"></script>

<!-- External JavaScript dependencies -->
<script src='https://cdn.jsdelivr.net/npm/@fullcalendar/core@6.1.8/index.global.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.8/index.global.min.js'></script>

{% endblock %}

coventGarden/studios/templates/home.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Header -->
{% block header %}

<header id="head">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<img class="navbar-brand" src="{% static 'studios/images/logo.png' %}" alt= "Covent Garden logo">
			</div>
			<a class="btn btn-action btn-lg" href="{% url 'booking' %}" role="button">Réserver un studio</a>
		</div>
	</div>
</header>

{% endblock %}



<!-- Page header -->
{% block page_header %}

{% endblock %}



<!-- Main content -->
{% block content %}

<!-- Content 1: Studios -->
<div class="row">
	<!-- Title -->
	<h2 class="text-center top-space">Les Studios</h2><br>

	<!-- Left: Text -->
	<div class="col-sm-6">
		<h4 class="fade-in text-justify">4 studios de répétition, 1 salle de concert et 1 bar dans le Val-d'Oise</h4>
		<h4 class="fade-in text-justify">Tous nos studios insonorisés sont équipés de matériel professionnel entretenu. <br >Un régisseur est là pour vous accueillir et prendre soin de vous.</h4>
		<h4 class="fade-in text-justify">Musicien amateur ou professionnel, le Covent Garden Studios est le lieu indépendant du 95 où vous pourrez exprimer toute votre créativité musicale.</h4>
		<h4 class="fade-in text-justify">Répétition, résidence ou concert, nous sommes là pour vous accompagnez techniquement.</h4>
	</div>

	<!-- Right: Image -->
	<div class="col-sm-6">
		<img src="{% static 'studios/images/presentation_studios.jpg' %}" alt="presentation_studios">
	</div>
</div>

<!-- Content 2: Concerts -->
<div class="row">
	<!-- Title -->
	<h2 class="text-center top-space">Les Concerts</h2><br>

	<!-- Left: Image -->
	<div class="col-sm-6">
		<p><img src="{% static 'studios/images/presentation_concerts.jpg' %}" alt="presentation_concerts"></p>
	</div>

	<!-- Right: Text -->
	<div class="col-sm-6">
		<h4 class="fade-in text-justify">La scène complètement équipée pour les lives, permettra aux groupes professionnels et amateurs de se produire dans d’excellentes conditions.</h4>
	</div>
</div>

<!-- Content 3 -->
<div class="row">
	<!-- Title -->
	<h3 class="text-center thin">Nos partenaires</h3>

	<!-- Images -->
	<div class="col-md-4 col-sm-6 highlight mx-auto">
		<a class="navbar-brand" href="https://coventgarden.fr/" target="_blank">
			<div class="crop-image-container text-center">
				<img class="crop-image" src="{% static 'studios/images/48Volt.png' %}" alt="48Volts">
			</div>
		</a>
	</div>

	<div class="col-md-4 col-sm-6 highlight mx-auto">
		<a class="navbar-brand" href="https://www.combo95.org/" target="_blank">
			<div class="crop-image-container text-center">
				<img class="crop-image" src="{% static 'studios/images/Combo95.png' %}" alt="Combo 95">
			</div>
		</a>
	</div>
	
	<div class="col-md-4 col-sm-6 highlight mx-auto">
		<a class="navbar-brand" href="https://www.brasseriedesutter.com/" target="_blank">
			<div class="crop-image-container text-center">
				<img class="crop-image" src="{% static 'studios/images/De_Sutter.png' %}" alt="De Sutter">
			</div>
		</a>
	</div>
</div>

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}

{% endblock %}

coventGarden/studios/templates/payment.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Insert title -->
{% block title %}

<title>Paiement accompte</title>

{% endblock %}



<!-- Insert main header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Insert content -->
{% block content %}

<head>
    <script src="https://js.stripe.com/v3/"></script>
</head>

<!-- Container -->
<div class="container">

	<!-- Breadcrumb -->
	<ol class="breadcrumb">
        <li><a href="{% url 'home' %}">Accueil</a></li>
        <li>Réservation</li>
		<li class="active">Paiement accompte</li>
	</ol> <!-- /Breadcrumb -->

	<!-- Main content -->
	<div class="row">

		<!-- Article -->
		<article class="col-sm-12 maincontent">

			<!-- Header -->
			<header class="page-header">
				<h1 class="page-title">Paiement accompte</h1>
			</header>
			
            <!-- Content 1: Form -->
			<form  action="{% url 'payment' %}" method="POST">
				<div class="justifie text-center text-muted">
					<p>ATTENTION : Une session réservée ne pourra être annulée 48h à l'avance</p>
					<p>Le paiment en ligne ne représente que la moitié du tarif total. Le reste sera payé le jour J, sur place.</p>
				</div>
				{% csrf_token %}
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<!-- Title / Text -->
							<h3 class="thin text-center">Paiement accompte</h3>
							<p class="text-center text-muted">Nous demandons le paiement d’un acompte pour la réservation.</p>

							<hr>

							<!-- Include form(s) here -->
							{% include "base/base_form.html" %}
                            <input type="hidden" name="salle_id" value="{{ salle.id }}">
                            <input type="hidden" name="user_id" value="{{ user.id }}">

							<hr>

							<!-- Button(s) -->
							<div class="row">
								<div class="col-xs-6 col-sm-5 col-md-4 col-lg-4">
									<button class="btn btn-secondary" type="button" onclick="window.location.href='{% url 'booking' %}'">Annuler</button>
								</div>
								<div class="col-xs-0 col-sm-2 col-md-4 col-lg-4">
								</div>
								<div class="col-xs-6 col-sm-5 col-md-4 col-lg-4">
									<button class="btn btn-success" type="submit" id="checkout-button">Confirmer</button>
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</form>
	
		</article> <!-- /Article -->

	</div> <!-- /Main content -->

</div> <!-- /Container -->

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

	<link rel="stylesheet" href="{% static 'studios/css/booking.css' %}">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}



<!-- Custom JavaScript file(s) -->
{% block scripts %}
<script src="{% static 'studios/js/payment.js' %}"></script>
<script>

	
	window.addEventListener('DOMContentLoaded', function() {
		$('#id_name').val("{{user.username}}");
		$('#id_email').val("{{user.email}}");
		$('#id_salle').val("{{salle.name}}");
		$('#id_duration').val("{{duration}}");
		$('#id_date_start').val("{{ start_date|date:'Y-m-d H:i:s' }}");
		$('#id_date_end').val("{{ end_date|date:'Y-m-d H:i:s' }}");
		$('#id_price').val("{{price}}");
		var form = document.querySelector('form');
		if (form) {
			var inputs = form.querySelectorAll('input');
			inputs.forEach(function(input) {
			input.setAttribute('readonly', 'readonly');
			});
		}
	});
</script>
{% endblock %}

coventGarden/studios/templates/payment_successful.html
{% extends 'base/base.html' %}
{% load static %}

<!-- Header -->
{% block header %}

<header id="head" class="secondary"></header>

{% endblock %}



<!-- Page header -->
{% block page_header %}

<header class="page-header">
	<h1 class="page-title">{{title}}</h1>
</header>

{% endblock %}



<!-- Main content -->
{% block content %}

<body>
  <h1>Merci pour votre paiement !</h1>
  <p>Nous vous remercions d'avoir effectué votre paiement.</p>
</body>

{% endblock %}



<!-- Custom CSS styles file(s) -->
{% block style %}

<link rel="stylesheet" href="{% static 'studios/css/payment_success.css' %}"/>

{% endblock %}


<!-- Custom JavaScript file(s) -->
{% block scripts %}


{% endblock %}

coventGarden/studios/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h3 style="margin-top: 0;">Success</h3>
</body>
</html>